# Generated by Django 5.0.6 on 2024-06-25 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Constituency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('manifesto', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('constituency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AlternativeVote.constituency')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AlternativeVote.party')),
            ],
        ),
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=100)),
                ('constituency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AlternativeVote.constituency')),
                ('vote1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote1', to='AlternativeVote.candidate')),
                ('vote2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote2', to='AlternativeVote.candidate')),
                ('vote3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote3', to='AlternativeVote.candidate')),
                ('vote4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote4', to='AlternativeVote.candidate')),
                ('vote5', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote5', to='AlternativeVote.candidate')),
            ],
        ),
    ]
