# Generated by Django 5.0.6 on 2024-06-26 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlternativeVote', '0002_alter_party_manifesto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='constituency',
            options={'verbose_name_plural': 'Constituencies'},
        ),
        migrations.AlterModelOptions(
            name='party',
            options={'verbose_name_plural': 'Parties'},
        ),
        migrations.AlterField(
            model_name='voter',
            name='vote1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vote1', to='AlternativeVote.candidate'),
        ),
        migrations.AlterField(
            model_name='voter',
            name='vote2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vote2', to='AlternativeVote.candidate'),
        ),
        migrations.AlterField(
            model_name='voter',
            name='vote3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vote3', to='AlternativeVote.candidate'),
        ),
        migrations.AlterField(
            model_name='voter',
            name='vote4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vote4', to='AlternativeVote.candidate'),
        ),
        migrations.AlterField(
            model_name='voter',
            name='vote5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vote5', to='AlternativeVote.candidate'),
        ),
    ]
