# Generated by Django 5.0.6 on 2024-06-26 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlternativeVote', '0003_alter_constituency_options_alter_party_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voter',
            name='vote1',
        ),
        migrations.RemoveField(
            model_name='voter',
            name='vote2',
        ),
        migrations.RemoveField(
            model_name='voter',
            name='vote3',
        ),
        migrations.RemoveField(
            model_name='voter',
            name='vote4',
        ),
        migrations.RemoveField(
            model_name='voter',
            name='vote5',
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preference', models.IntegerField(default=0)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AlternativeVote.candidate')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AlternativeVote.voter')),
            ],
        ),
    ]
